import { Table } from "ts-sql-query/Table";
import { PostgresConnection } from "./connection";

export const tTabs = new class TCompany extends Table<PostgresConnection, "TTabs"> {
  id = this.autogeneratedPrimaryKey("id", "int");
  label = this.column("tab_label", "string");
  value = this.column("tab_value", "string");
  type = this.column("tab_type", "string");
  constructor() {
    super("tabs");
  }
}();

export const tArticles = new class TCompany extends Table<PostgresConnection, "TTabs"> {
  id = this.autogeneratedPrimaryKey("id", "int");
  tabId = this.column("tab_id", "int");
  label = this.column("label", "string");
  value = this.column("_value", "string");
  content = this.column("content", "string");
  type = this.column("_type", "string");
  picture = this.column("picture", "string");
  links = this.optionalColumnWithDefaultValue("picture", "string");
  constructor() {
    super("articles");
  }
}();
